
  
title: minpeter DEV blog
author: minpeter
email: kali2005611@gmail.com
url: https://minpeter.github.io
baseurl: ""
description: >
í•œì„¸ì‚¬ì´ë²„ë³´ì•ˆê³ ë“±í•™êµ í•´í‚¹ë³´ì•ˆê³¼.
Today I Learned, dev log, Etc... 
ğŸ™Œ ì˜¤ëŠ˜ë„ ì—´ì‹¬íˆ!!
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag