baseURL: "https://minpeter.github.io/"
title: minpeter DEV blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
sitemap:
  changefreq: "always"
  filename: "sitemap.xml"
  priority: 0.5

googleAnalytics: G-6FQKWLZK1S

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

staticDir:
  - "static"
  - "content/posts/TIL/images"
  - "content/posts/server/images"
  - "content/posts/linux/images"
  - "content/posts/blog/images"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: minpeter DEV blog
  description: "Posts related to computer development"
  keywords: [Blog, computer, linux, terminal, server, development, programming]
  author: minpeter
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/fav.ico"
    favicon16x16: "<link / abs url>"
    favicon32x32: "/fav.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "ğŸš€ minpeter DEV blog"
    # icon: /icon.png
    # iconHeight: 35

  # # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: minpeter
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  # buttons:
  #   - name: Posts
  #     url: posts
  #   - name: Tags
  #     url: tags

  # home-info mode
  homeInfoParams:
    Title: minpeter
    Content: ğŸ« HCSHS | ğŸ’˜ Terminal | ğŸ§ Linux

  socialIcons:
    - name: twitter
      url: "https://twitter.com/minpeter2"
    - name: instagram
      url: "https://instagram.com/minpeter2"
    - name: github
      url: "https://github.com/minpeter"
    - name: rss
      url: "https://minpeter.github.io/index.xml"

  analytics:
    google:
      SiteVerificationTag: "RNVL00kQq_OXnyYh9S4hgL35tPhS5wdFNf_qNiXhxS8"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/minpeter/minpeter.github.io/blob/main/content"
    Text: "ğŸ“ Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archives
      name: ğŸ“¦Archives
      url: /archives/
      weight: 10
    - identifier: categories
      name: ğŸ—ƒï¸Categories
      url: /categories/
      weight: 20
    - identifier: search
      name: ğŸ”Search
      url: /search/
      weight: 30
    - identifier: tags
      name: ğŸ·ï¸Tags
      url: /tags/
      weight: 40

  # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
  # pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
